spring:
  social:
    facebook:
      app-id: 2230927883904013
      app-secret: 85945bc4915b8088bea8633fe43a903e
    twitter:
      app-id: yix4Ai9xDbWBKV3yFPFGs8Nkf
      app-secret: 9rXtdeYe5v3wmGR5E96ubiXRDeWzZFgRt2ZYdgSKeQFivw0OtD
